- CHANGES.rst
- plone/app/dexterity/browser/default_page_warning.pt
so that message strings could go into POT file and get translated in PO files.
> Add i18n:domain for Default Page Warning Template.

- CHANGES.rst
@staeff found out that plone.app.dexterity 2.0.12 zip file on PyPi is completely broken.
Make sure that everyone is aware of it.
Fixes: https://github.com/plone/plone.app.dexterity/issues/155
> Note about brown bag release

- CHANGES.rst
- docs/advanced/custom-add-and-edit-forms.rst
The documentation in this link (http://docs.plone.org/external/plone.app.dexterity/docs/advanced/custom-add-and-edit-forms.html#custom-add-forms) has been updated like in (http://docs.plone.org/develop/plone/content/dexterity.html#custom-add-form-view)
instead: ..interfaces.IDexterityFTI
use full path: plone.dexterity.interfaces.IDexterityFTI
> Fixed an adapter path at custom add forms documentation.

- CHANGES.rst
- plone/app/dexterity/browser/types.py
Fix plone/Products.CMFPlone#768.
Restrict allowed field types to regular types (so plone.app.users do not show up)
> Restrict allowed field types to regular types

- CHANGES.rst
- docs/grok/testing/integration-tests.rst
- docs/testing/integration-tests.rst
- plone/app/dexterity/tests/test_constrains.py
- plone/app/dexterity/tests/test_export.py
- plone/app/dexterity/tests/test_import.py
- plone/app/dexterity/tests/test_nextprevious.py
- plone/app/dexterity/tests/test_permissions.py
- plone/app/dexterity/tests/test_upgrades.py
- setup.py
Since python 2.7 unittest2 was already merged with unittest.
> No need for unittest2

- CHANGES.rst
- plone/app/dexterity/behaviors/tests/test_id.py
No longer rely on deprecated bobobase_modification_time from Persistence.Persistent.
see changelog for Zope 4.0a1: https://github.com/zopefoundation/Zope/blob/master/CHANGES.rst
> Remove bobobase_modification_time

- CHANGES.rst
- plone/app/dexterity/tests/test_upgrades.py
- plone/app/dexterity/upgrades/to2001.py
If an object already has a UID value on the catalog there is no need to add it again.
In cases where *LOTS* of objects get returned by the catalog call it can dramatically impact the upgrade.
This pull request is a backports https://github.com/plone/plone.app.dexterity/pull/189 for 2.0.x line
> Avoid re-adding the UUID

- plone/app/dexterity/permissions.py
I have this behavior:
```python
from plone.app.z3cform.widget import AjaxSelectFieldWidget
from plone.autoform import directives
from plone.autoform.interfaces import IFormFieldProvider
from plone.supermodel import model
from zope import schema
from zope.interface import provider
from . import _
@provider(IFormFieldProvider)
class IRelatedEmployees(model.Schema):
employees = schema.Tuple(
title=_(u'label_employees', default=u'Related employees'),
description=_(
u'help_employees',
default=u'Related employees for this document.'
),
value_type=schema.Choice(
title=_(u'label_employees', default=u'Related employees'),
vocabulary='zimmhrm.vocabularies.employees',
),
required=False,
)
directives.widget(
'employees',
AjaxSelectFieldWidget,
vocabulary='zimmhrm.vocabularies.employees'
)
```
And …
> Fix non existing self._request with schema.Choice value_type.

- plone/app/dexterity/__init__.py
- plone/app/dexterity/behaviors/configure.zcml
- plone/app/dexterity/behaviors/discussion.py
- plone/app/dexterity/behaviors/exclfromnav.py
- plone/app/dexterity/behaviors/id.py
- plone/app/dexterity/behaviors/metadata.py
- plone/app/dexterity/behaviors/nextprevious.py
- plone/app/dexterity/browser/add_type.py
- plone/app/dexterity/browser/behaviors.py
- plone/app/dexterity/browser/clone_type.py
- plone/app/dexterity/browser/configure.zcml
- plone/app/dexterity/browser/container.pt
- plone/app/dexterity/browser/default_page_warning.pt
- plone/app/dexterity/browser/fields.py
- plone/app/dexterity/browser/import_types.py
- plone/app/dexterity/browser/item.pt
- plone/app/dexterity/browser/layout.py
- plone/app/dexterity/browser/modeleditor.py
- plone/app/dexterity/browser/overview.pt
- plone/app/dexterity/browser/types_listing.pt
- plone/app/dexterity/browser/typesformwrapper.pt
- plone/app/dexterity/configure.zcml
- plone/app/dexterity/events.zcml
- plone/app/dexterity/locales/update.sh
- plone/app/dexterity/profiles/default/actions.xml
- plone/app/dexterity/profiles/default/controlpanel.xml
plone.app.dexterity is an official Plone core package,
thus their translations belong to plone.app.locales.
This commit removes the plone.app.dexterity domain and changes it for
plone.
This fixes:
https://github.com/plone/plone.app.dexterity/issues/158
Needs to be merged together with https://github.com/plone/plone.schemaeditor/pull/35
> Use plone i18n domain

- CHANGES.rst
- docs/reference/form-schema-hints.rst
- fixed: historic and confusing ``... import directives as from`` changed.
- fixed: wrong usage of ``primary`` and ``fieldset`` corrected.
- overhaul: introduction
- overhaul: table style 
- overhaul: code style
/cc @svx @polyester may you have a quick look?
> Overhaul of chapter form-schema-hints.rst

- CHANGES.rst
- plone/app/dexterity/behaviors/configure.zcml
- plone/app/dexterity/behaviors/exclfromnav.py
- setup.py
It still defaults to ``False``. An alternative adapter which defaults to ``True`` is provided but not registered. 
Custom adapters are possible too.
> The defaults of exclude from navigation is now obtained from an adapter.

- CHANGES.rst
- plone/app/dexterity/browser/behaviors.py
TTW behaviors selection of the name is now bound to the registration, prior it was bound to the interface.  But interfaces may be used by more than one registered behavior.
> TTW behaviors selection of the name is now bound to the registration

- CHANGES.rst
- docs/behaviors/testing-behaviors.rst
I believe it works in Plone 5 and Plone 4.
> Add example of testing a dexterity type using a behavior. fix #229

- CHANGES.rst
- plone/app/dexterity/browser/configure.zcml
- plone/app/dexterity/browser/folder_listing.pt
- plone/app/dexterity/browser/folder_listing.py
This is a necessary counterpart to https://github.com/plone/Products.CMFPlone/pull/1839 and https://github.com/plone/Products.ATContentTypes/pull/39 to move content views from the plone_content layer in CMFPlone to ATContentTypes.
The Dexterity container view looks for the folder_listing view to get the macro for rendering contained items, so we need this to be present even if ATContentTypes or plone.app.contenttypes aren't installed (such as in tests)
> Add generic version of folder_listing view & macro

- CHANGES.rst
- plone/app/dexterity/behaviors/metadata.py
- plone/app/dexterity/behaviors/tests/test_metadata.py
- setup.py
When setting the Description field, do not remove new lines but keep the input as-is.
Instead remove new lines in the plone.dexterity ``Description`` metadata accessor.
> Do not remove newlines in description setter

- CHANGES.rst
- plone/app/dexterity/permissions.py
Fix issue with field permissions check on add forms when the parent (=container) has no "Modify portal content" permission.
New: For add forms use the "Add portal content" permission as default field permission. One can not have modify on a not-yet-created item.
As great side effect vocabularies for i.e. AjaxSelectWidget from ``plone.app.content``, which are using the check, are working on add forms in a context w/o "Modify portal content".
> Fix permission check for add forms

- CHANGES.rst
- plone/app/dexterity/factories.py
Remove the transaction.begin call before creating a dx object.
Remove the transaction.commit call after creating a dx object.
Fixes #243
> Remove the transaction.begin and transaction.commit calls

- CHANGES.rst
- plone/app/dexterity/browser/behaviors.pt
- plone/app/dexterity/browser/container.pt
- plone/app/dexterity/browser/item.pt
Fixes an error with displaying TTW Dexterity types via plone.app.contenttypes full_view.
> Don't break if types are without widgets or groups.

- news/276.bugfix
- plone/app/dexterity/factories.py
Fixes https://github.com/plone/plone.app.dexterity/issues/276
> Release upload lock when name chooser fails. [2.3.x]

- news/284.bugfix
- plone/app/dexterity/behaviors/constrains.py
- plone/app/dexterity/tests/test_constrains.py
This is the same fix as in https://github.com/plone/plone.app.dexterity/pull/264 but for master branch
> Do not acquire constrain_types_mode from parent when not defined.

- news/268.feature
- plone/app/dexterity/factories.py
- plone/app/dexterity/permissions.py
- plone/app/dexterity/tests/test_permissions.py
Avoid deprecation warnings after cleanup over there:
- IWidgetsLayer->IPloneFormLayer
- import IFieldPermissionChecker from plone.app.z3cform
> reflect moves from plone.app.widgets to plone.app.z3cform

- news/268.feature
- plone/app/dexterity/factories.py
- plone/app/dexterity/permissions.py
- plone/app/dexterity/tests/test_permissions.py
Reverts plone/plone.app.dexterity#287
2nd trial...
> Revert "Revert "reflect moves from plone.app.widgets to plone.app.z3cform""

- news/312.bugfix
- plone/app/dexterity/behaviors/nextprevious.py
It would break with https://github.com/plone/plone.app.z3cform/pull/114/commits/7c0688e
> Do not require nextPreviousEnabled.

- news/313.bugfix
- plone/app/dexterity/tests/editing.rst
> Refs #313 - Fix tests to match plone.dexterity dynamic schema name

- news/313.bugfix
- plone/app/dexterity/tests/editing.rst
When a schema is changed twice within the same second, the newest changes do not make it to the schema cache.
So we wait till the next second.
See comments here: https://github.com/plone/plone.app.dexterity/issues/313
> Fix schema tests by waiting longer so the schema is invalidated.

- docs/prerequisite.rst
The docs about the usage of bobtemplates.plone seems a bit out of sync and the procedure for creating a package seems slightly different than described in https://docs.plone.org/external/plone.app.dexterity/docs/prerequisite.html#creating-a-package 
I think that other pages in the docs should probably be updated.
> Update info about bobtemplates.plone usage (subtemplate content_type)

- news/292.bugfix
- plone/app/dexterity/tests/robot/test_types.robot
I'm in the process of trying to unify Robot test setups and teardowns. This is a part of that effort.
In tandem with https://github.com/plone/plone.app.robotframework/pull/110
Closes https://github.com/plone/plone.app.dexterity/issues/292
> Default to a 4K x 4K browser window in Robot tests

- news/337.bugfix
- setup.py
Warning on startup:
```
pkg_resources/_vendor/packaging/specifiers.py:273: DeprecationWarning:
Creating a LegacyVersion has been deprecated and will be removed in the next major release
```
It fell over `plone.namedfile[scales] >=1.0b5dev-r36016`.
I simply removed all the dev/alpha/beta markers from all requirements.
> Fix warning about legacy version specifiers in setup.py.

- news/106.bugfix
- setup.py
See https://github.com/plone/plone.namedfile/issues/106
> Depend on `plone.namedfile` core instead of its empty `[scales]` extra.

- news/106.bugfix
- setup.py
Backport of PR #338 for Plone 5.2.
> Depend on `plone.namedfile` core instead of its empty `[scales]` extra. [2.6.x]

- news/3473.bugfix
- plone/app/dexterity/browser/modeleditor.py
Fixes https://github.com/plone/Products.CMFPlone/issues/3473
> Modeleditor: when there is no model_source yet, show the model_file.

- news/346.bugfix
- plone/app/dexterity/textindexer/converters.py
That should not be done in Plone core.
This is in the new `textindexer` module.
> Replaced use of plone.api.

- news/169.bugfix
- plone/app/dexterity/textindexer/tests/configure.zcml
The 'name' property may become required.
See https://github.com/plone/plone.dexterity/issues/169
> Tests: add names to behaviors.

- news/358.bugfix
- plone/app/dexterity/browser/modeleditor.pt
- plone/app/dexterity/tests/editing.rst
Use the page template's structure keyword when inserting the escaped HTML into the modeleditor's textarea. This allows the source code pattern to properly parse and display the XML for editing.
Fixes: #357
Together:
https://github.com/plone/plone.staticresources/pull/259
https://github.com/plone/plone.app.dexterity/pull/358
> Modeleditor: Don't double escape the xml.

- news/359.bugfix.1
- news/359.bugfix.2
- news/359.bugfix.3
- plone/app/dexterity/browser/modeleditor.pt
- plone/app/dexterity/browser/modeleditor.py
- Use the tal engine to escape HTML via non-structure variable insertion.
- Restore BBB method.
> Modeleditor simplify

- .editorconfig
- .meta.toml
- dependabot.yml
- news/+meta.internal
- pyproject.toml
- tox.ini
Mostly this PR demonstrates that currently we need to manually make some adjustments to `tox.ini` if we have a package that we need to test on Plone 6.1.  That seems the only file that needs changes, which is good.
See https://github.com/plone/meta/issues/210
> Config with default template 5d669ee9

- news/393.tests
- plone/app/dexterity/tests/robot/test_types.robot
This is part of https://github.com/plone/Products.CMFPlone/issues/3813
- port robot tests
> Port robot test

- news/407.bugfix
- plone/app/dexterity/textindexer/__init__.py
- plone/app/dexterity/textindexer/tests/test_basic_behavior.py
It was missing from new texindexer configuration
> Re-enable subjects into SearchableText indexing
