- CHANGES.rst
- plone/app/dexterity/browser/types_listing.pt
For info, please see https://github.com/plone/mockup/pull/485
> Rename pat-modal to pat-plone-modal.

- docs/reference/widgets.rst
The correct field for NamedImageFieldWidget is came from plone.formwidget.namedimage.
Also added the NamedBlobFile and NamedBlobImage fields.
> Mr tango patch widgets reference

- plone/app/dexterity/behaviors/id.py
- plone/app/dexterity/behaviors/tests/test_id.py
fix https://github.com/plone/Products.CMFPlone/issues/623
> Unlock before changing id

- CHANGES.rst
- plone/app/dexterity/behaviors/configure.zcml
> Remove superfluous 'for' in behaviors zcml w/o factory.

- docs/advanced/vocabularies.rst
nothing important, but helps the docs team get their error count down ;-)
> tiny RST error

- CHANGES.rst
- plone/app/dexterity/browser/modeleditor.js
- plone/app/dexterity/browser/modeleditor.pt
- plone/app/dexterity/tests/editing.txt
closes https://github.com/plone/Products.CMFPlone/issues/895
> Issue 895 - Fix ace editor javascript reference

- CHANGES.rst
- plone/app/dexterity/browser/types_listing_row.pt
replaces https://github.com/plone/plone.app.dexterity/pull/187 (rebased)
https://github.com/plone/Products.CMFPlone/issues/1151
> fix icons in dexterity types list 

- docs/advanced/custom-add-and-edit-forms.rst
> docs: Corrected registration of custom add form

- CHANGES.rst
- docs/advanced/event-handlers.rst
> update event handler docs

- docs/behaviors/schema-only-behaviors.rst
This is a fix for https://github.com/plone/documentation/issues/561
> Fix typo form ->from

- CHANGES.rst
- plone/app/dexterity/behaviors/configure.zcml
> assign shortnames to behaviors as supported by plone.behavior

- CHANGES.rst
- plone/app/dexterity/factories.py
fixes https://github.com/plone/Products.CMFPlone/issues/1553
> Correct how Type is looked Up

- docs/advanced/custom-add-and-edit-forms.rst
- fix a header
- update a link
- fix a typo
> Minor cleanups

- CHANGES.rst
- docs/reference/standard-behaviours.rst
just overhauled the "Standard behaviors" reference page.
> Documentation: Shortnames added and some missing behaviors added.

- CHANGES.rst
- docs/custom-views.rst
- docs/model-driven-types.rst
- docs/prerequisite.rst
- docs/schema-driven-types.rst
Update tutorial sections of documentation to use mr.bob and bobtemplates.plone.
> Cleanout zopeskel; replace with mr.bob. Fixes #220

- CHANGES.rst
- plone/app/dexterity/interfaces.py
> import from canonical source

- CHANGES.rst
- plone/app/dexterity/behaviors/exclfromnav.py
> Make exclude_from_nav optional.

- CHANGES.rst
- plone/app/dexterity/locales/nl/LC_MESSAGES/plone.app.dexterity.po
- plone/app/dexterity/locales/plone.app.dexterity.pot
> Update Dutch translations by merging them

- news/279.bugfix
- plone/app/dexterity/browser/import_types.py
Fixed by added missing StringIO import
Fixed #279
> Dexterity Import Type Profile fails

- news/268.feature
- plone/app/dexterity/factories.py
- plone/app/dexterity/permissions.py
- plone/app/dexterity/tests/test_permissions.py
Reverts plone/plone.app.dexterity#286
> Revert "reflect moves from plone.app.widgets to plone.app.z3cform"

- news/290.bugfix
- plone/app/dexterity/browser/add_type.py
- plone/app/dexterity/browser/behaviors.py
- plone/app/dexterity/tests/editing.rst
> Moved TTW creation of content types to use and add/remove named behaviors

- docs/reference/form-schema-hints.rst
- news/294.bugfix
Replaced IBasic.description with IDublinCore.description
> Updated Form Schema Hints

- docs/behaviors/creating-and-registering-behaviors.rst
- news/doccreatebehavior.bugfix
Adjusted imports etc. so they work for Plone 5.1.2
Note to reviewer: we might want to use a more recent package (not something on svn.plone.org) as an example for dexterity docu. If you could point me to a good example I'd be happy to adjust the docu to this.
> Update docu for creating dexterity behaviors

- news/296.bugfix
- plone/app/dexterity/browser/add_type.py
- plone/app/dexterity/browser/behaviors.py
- plone/app/dexterity/tests/editing.rst
Fixes #296
Closes plone/Products.CMFPlone#2881
> Behavior should be saved as native strings

- docs/prerequisite.rst
- news/305.bugfix
Use new and improved mr.bob command
Avoid https://github.com/plone/bobtemplates.plone/issues/277
> Fixes #305

- news/313.bugfix
- plone/app/dexterity/tests/editing.txt
> 2.0.x - Fix tests to match plone.dexterity dynamic schema name

- news/3209.bugfix
- plone/app/dexterity/browser/modeleditor.py
See https://github.com/plone/Products.CMFPlone/issues/3209
> Modeleditor: do not resolve entities, to avoid xml vulnerabilities

- news/329.bugfix
- setup.py
> Remove cyclic dependency with Products.CMFPlone.

- docs/advanced/catalog-indexing-strategies.rst
- news/2780.feature
- plone/app/dexterity/configure.zcml
- plone/app/dexterity/permissions.py
- plone/app/dexterity/textindexer/__init__.py
- plone/app/dexterity/textindexer/behavior.py
- plone/app/dexterity/textindexer/configure.zcml
- plone/app/dexterity/textindexer/converters.py
- plone/app/dexterity/textindexer/directives.py
- plone/app/dexterity/textindexer/indexer.py
- plone/app/dexterity/textindexer/interfaces.py
- plone/app/dexterity/textindexer/schemaeditor.py
- plone/app/dexterity/textindexer/supermodel.py
- plone/app/dexterity/textindexer/testing.py
- plone/app/dexterity/textindexer/tests/__init__.py
- plone/app/dexterity/textindexer/tests/behaviors.py
- plone/app/dexterity/textindexer/tests/behaviors.rst
- plone/app/dexterity/textindexer/tests/configure.zcml
- plone/app/dexterity/textindexer/tests/helpers.py
- plone/app/dexterity/textindexer/tests/test_basic_behavior.py
- plone/app/dexterity/textindexer/tests/test_behaviors.py
- plone/app/dexterity/textindexer/tests/test_directives.py
- plone/app/dexterity/textindexer/tests/test_schemaeditor.py
- plone/app/dexterity/textindexer/tests/test_supermodel_handler.py
- plone/app/dexterity/textindexer/tests/test_utils.py
- plone/app/dexterity/textindexer/utils.py
- setup.cfg
- setup.py
Integration of `collective.textindexer` -> `plone.app.dexterity.textindexer`.
https://github.com/plone/Products.CMFPlone/issues/2780
> PLIP 2780: textindexer

- docs/advanced/catalog-indexing-strategies.rst
- news/347.bugfix
- plone/app/dexterity/textindexer/configure.zcml
> better naming and description of textindexer in behaviors control panel

- news/3695.bugfix
- plone/app/dexterity/browser/modeleditor.py
- plone/app/dexterity/tests/editing.rst
Fixes https://github.com/plone/Products.CMFPlone/issues/3695
> Fix XMLSyntaxError when saving model source in the modeleditor.

- news/4126.bugfix
- plone/app/dexterity/browser/fields.py
See https://github.com/plone/Products.CMFPlone/issues/4126
> Replace pkg_resources

- news/4126.bugfix
- plone/app/dexterity/browser/fields.py
- pyproject.toml
> fix: replace pkg_resources with importlib

- news/+nextprev.feature
- plone/app/dexterity/behaviors/nextprevious.py
- plone/app/dexterity/tests/test_nextprevious.py
(So that it can be serialized differently by plone.restapi)
> Include obj in results from INextPreviousProvider adapter
